[build]
  base = "blog"
  publish = "_site"
  command = "npm run build"

[[redirects]]
from = "/blog/admin"
to = "/blog/admin/index.html"
status = 200

[[redirects]]
from = "/blog/admin/"
to = "/blog/admin/index.html"
status = 200
