site_url: https://aircapitalcleaning.com

backend:
  name: github
  repo: AirCapitalCleaningCo/AirCapitalCleaningCo
  branch: main
  base_url: https://api.netlify.com
  site_id: 75d3af84-8629-4e74-8a4f-fb0285559f15

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "blog/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
